### ISSUE TITLE
API - Appointment model time

### ISSUE THREAD

**Issue by amayers** [workpathco/support#1]
The `Appointment`model has a `time` property that is presumably the start time. Our designers had discussed having an estimated `end_time` so that users can more easily plan their day's schedule.

**Comment by iggbodiam** [comment]
Is this issue a demonstration and I can close it?

**Comment by amayers** [comment]
@iggbodiam no, its for @hpainter

**Comment by ghost** [comment]
Agreed. I'm going to change `time` to `start_time` and add a new `end_time`

**Comment by ghost** [comment]
This is changed on api-demo now.
