### ISSUE TITLE
User's home_radius and location_radius not changed after a PUT

### ISSUE THREAD

**Issue by amayers** [workpathco/support#14]
When using a PUT to `/users/<id>` with a body that contains `{ "location_radius": 100 }` the returned user still has the default value and not the new one that is passed in the PUT. No errors are thrown. Applies to `location_radius` & `home_radius` properties on a `User`

**Comment by ghost** [comment]
This should be working now.  Updates to user #1009 to set the `{"home_radius": 100, "location_radius": 25}` return the expected new values.

**Comment by amayers** [comment]
Just tried it and no change

**Comment by ghost** [comment]
Resolved with 'Content-Type' header
