### ISSUE TITLE
PUT on people endpoint fails to create/set home address

### ISSUE THREAD

**Issue by amayers** [workpathco/support#15]
A `PUT` to `/people/<id>` with a body that contains a person's details including a new address with the `default` label to set it as home, gets a 403 response.

**Comment by ghost** [comment]
Could you give me an example of your request body for this?  That way I can make sure we accept your updates.  In our clients we are doing separate calls to `PUT /addresses/x` and `PUT /people/x`, but I don't see why we should force you to.

**Comment by ghost** [comment]
PUT requests to /people/:id now supports payloads like

`{"addresses":[ {"id":1010,"city":"Spokane"} ]}`
