### ISSUE TITLE
PUT to specialists fails with 400 error

### ISSUE THREAD

**Issue by amayers** [workpathco/support#17]
`PUT` to `/specialists/1001` fails with a 400 error

```
{
	"status": "other",
	"application_score": 60,
	"quality_rating": 51,
	"id": 1001,
	"schedule": {
		"sunday": [
			"09:00:00",
			"17:00:00"]
	}
}
```

returns:

```
{
	"status": 400,
	"message": "Validation isIn failed",
	"error": {
		"status": 400
	}
}
```

@hpainter

**Comment by ghost** [comment]
The error message needs to be more helpful, but this is the right response.  The 'status' must be one of 'Applicant','Training','Active','Rejected','Repo','Cancelled'.   Which you guys should probably not be updating in any case, so probably safest to leave it out entirely.

**Comment by amayers** [comment]
Ah, the docs didn't have all of possible statuses so I grouped everything into either `Active` or `Other`.
