### ISSUE TITLE
Need more filter options for /appointments

### ISSUE THREAD

**Issue by amayers** [workpathco/support#18]
We need a way to filter the `/appointments` endpoint so we can request all appointments for the current user that have been accepted, but not completed. Also we need to be able to request appointments that have been completed (also for the current user). 
@hpainter

**Comment by amayers** [comment]
Along with this filtering, we should get a way to get appointments that have not been accepted.

**Comment by ghost** [comment]
Filters are available now. 
- `status=Published` will get you just non-accepted appointments
- `status=Accepted` will get you just the accepted appointments
- `Completed`+`Cancelled` for completed or cancelled

Let me know if you see any issues with these.
