### ISSUE TITLE
PUT user response is incomplete

### ISSUE THREAD

**Issue by JoeAcanfora** [workpathco/support#25]
PUT user responds with: 

{"roles":["admin-basic"],"id":1004,"email":"pbotomist@example.com","email_verified_at":null,"last_login_at":null,"tos_accepted_at":null,"latitude":37.5259,"longitude":-77.4396,"gps_updated_at":null,"home_radius":300,"location_radius":95,"created_at":"2016-12-14T14:38:29.000Z","updated_at":"2016-12-15T18:01:27.000Z","person":{"id":1003,"name":"Philomena B. Botomist","dob":"1980-12-02T00:00:00.000Z","gender":"Female","phone":"804-867-5309","email":"pbotomist@example.com","photo_url":"https://iggbo-app-assets.s3.amazonaws.com/334d7325-a0cd-44b7-9aef-af337d26c855.jpg","created_at":"2016-12-14T14:38:29.000Z","updated_at":"2016-12-15T18:01:39.000Z","addresses":[{"id":1102,"label":"default","street":"8717 Grand Summit Rd","street2":"Suite 5","city":"North Chesterfield","state":"VA","zip":"23235","country":"United States","phone":null,"latitude":37.5311,"longitude":-77.558,"created_at":"2016-12-14T14:38:29.000Z","updated_at":"2016-12-14T16:29:54.000Z"}],"tags":[{"id":1001,"name":"Centrifuge","color":"#ff0000","description":"Has access to centrifuge","locked":false,"alert":false,"created_at":"2016-12-14T14:38:29.000Z","updated_at":"2016-12-14T14:38:29.000Z"}]},"devices":[]}

Which does not include Specialist.

**Comment by ghost** [comment]
Fixed now on api-demo
