### ISSUE TITLE
Appointment has a status of `Accepted` but the specialist isn't me

### ISSUE THREAD

**Issue by amayers** [workpathco/support#26]
When calling `/appointments?page=1&limit=250&status=Accepted` I am getting an appointment ID `1014` who's specialist ID is `3304`, but the user making that requests has a specialist ID `1001`. I shouldn't see accepted requests for other specialists.

**Comment by ghost** [comment]
O_o  No you definitely should not be seeing them. Glad you caught this.  Fixed on demo server now.
