### ISSUE TITLE
Need sort control for /appointments

### ISSUE THREAD

**Issue by amayers** [workpathco/support#28]
We need a flag that controls the sorting of the `/appointments` endpoint. 
Personally I would prefer it to be called `newestFirst = true/false`, but `ascending = true/false` also works.

This is needed because we want the oldest first (current behavior) for the accepted & requests lists, but the history list should show the newest first similar to how almost all financial apps do their sorting.

**Comment by ghost** [comment]
Added a `newestFirst` param to `GET /appointments`.  `newestFirst=true` sorts results by `start_time` descending.  `newestFirst=false` sorts by `start_time` ascending.

**Comment by amayers** [comment]
I don't see this update in the docs. Is that just because you haven't pushed this change?
