### ISSUE TITLE
API - Appointment search radius

### ISSUE THREAD

**Issue by amayers** [workpathco/support#3]
The API supports searching for appointments within a `radius` in miles around a `lat/lon`. Could we make that `radius` optional and interchangeable with `travel_duration` that is the maximum # of minutes in travel time that the user is willing to do?

**Comment by ghost** [comment]
We can, but I strongly would prefer not to.  The reason being that the travel time calculation is heavy and requires calls to third party services, and for a collection set that could mean a lot of driving time calculations just to get the index.

My preference here is to use a naive circular radius to do a fast geo filter on the appointments, and only when someone wants to fetch the details on a specific appointment will we do the more expensive calculation.

**Comment by amayers** [comment]
Seems reasonable
