### ISSUE TITLE
/appointments is not filtering out appointments accepted by other users

### ISSUE THREAD

**Issue by amayers** [workpathco/support#33]
when logged in via user id/specialist id/person id 3302, and I call `/appointments/` with multiple status params so that I get all appointments `>= accepted` & `< completed` I will get my appointments, along with appointments that are in those states for other users. Most commonly specialist ID 1001 (Philomena B Botomist).

**Comment by ghost** [comment]
This is because your user has an `admin` role attached to it.  Normal users will not see the additional appointments.  I would say use a different account for testing that is just a basic 'user'.  (the 'someguy@mobelux.com' login is set up that way)
