### ISSUE TITLE
Submitting a problem changes the appointment status

### ISSUE THREAD

**Issue by amayers** [workpathco/support#35]
When POSTing `/appointments/1242/cancel` with `{ "code" : [103] }` the appointment's status is changed from `arrived` to `preview`, however 103 is not inside the array of codes that should cancel the appointment: `[200,201,202,203,204,300,301,500,501,600,601,602,603]`

**Comment by ghost** [comment]
Good point.  I was assuming that any post to this endpoint was going to result in either a cancellation or an abandonment of the appointment, but that's just not the case.  I will back that off and leave it up to the customer support folks...

**Comment by amayers** [comment]
`[200,201,202,203,204,300,301,500,501,600,601,602,603]` problems will still cancel the appointment?
