### ISSUE TITLE
Track 'quantity' of a procedure

### ISSUE THREAD

**Issue by ghost** [workpathco/support#36]
For appointments that require a particular procedure to be performed multiple times, we'll need a 'quantity' property.  For example, to indicate that two identical tubes need to be collected: 

```json
{
      "data": {
        "equipment_id": 1013,
        "action": "Collect",
        "value": "10"
      },
      "form": [],
      "id": 19251,
      "name": "Collect 1 Streck Tube",
      "stage": "In Progress",
      "stage_idx": 10,
      "quantity": 2,
      "type": "Processing",
      "created_at": "2016-12-28T13:52:17.000Z",
      "updated_at": "2017-01-05T19:03:10.000Z"
 }
```

**Comment by amayers** [comment]
Does it make sense for the `quantity` to be a top level procedure property? It seems like it should be in the `data` since only processing types will need it.

**Comment by ghost** [comment]
I think you're right, and the more I look at this one the more troublesome it becomes to have it as a top level property...we don't want more than one of any other type of procedure.  So, let's do this instead:

- Move `procedure.quantity` to  `procedure.data.quantity`.
- It is not used in the app anywhere currently, so just continue to ignore the `data.value` number for these procedures.
