### ISSUE TITLE
Param to remove 'Add Services' procedure from appointment

### ISSUE THREAD

**Issue by ghost** [workpathco/support#38]
In `PUT /appointments/:id`, check for a parameter `doneWithAddingServices=true` and if present then remove any `appointment.procedure` for adding new services.

**Comment by iggbodiam** [comment]
@hpainter   I'm not sure how this operates but PUT /appointments/[id]  did not return the field "doneWithAddingServices=true"  or false.  the field is simply omitted.

Is there a certain PUT instruction requred to summon that response?  thanks
