### ISSUE TITLE
Creating a new appointment fails

### ISSUE THREAD

**Issue by amayers** [workpathco/support#41]
When creating a new appointment with the following settings:

![screen shot 2017-01-17 at 9 58 16 am](https://cloud.githubusercontent.com/assets/868103/22025473/af613784-dc9b-11e6-9b39-b5ea209bea65.png)

You always get a 400 error:

![screen shot 2017-01-17 at 9 58 31 am](https://cloud.githubusercontent.com/assets/868103/22025475/b13adc0e-dc9b-11e6-9f9e-3b0f1fea9b64.png)

**Comment by ghost** [comment]
the message is correct but the UI was allowing something it shouldn't have.  The form has been fixed to disable statuses other than 'Preview' for new appts.
