### ISSUE TITLE
When an appointment is accepted, any conflicting appointments should be removed from feed as well

### ISSUE THREAD

**Issue by Beverly-Ann** [workpathco/support#43]

**Comment by ghost** [comment]
I think I disagree on this one, but I also suspect I would be outvoted.  If I were the user, I would want to see schedule-conflicting appts in the available list just in case I want to drop-add for something more attractive

**Comment by epeloke** [comment]
I agree with Justin.   If they try to accept but have a conflicting appointment we will show them an error but shouldn't hide the opportunity from them.
