### ISSUE TITLE
Phone number API documented without Country Code?

### ISSUE THREAD

**Issue by iggbodiam** [workpathco/support#5]
API Document displays relative phone number format xxx-xxx-xxxxx
Expected to include country code string as well:

Country: +[integer]
Phone: [string]   //String allows adding off brackets and dashes. ( do we want to store it as is in the DB or have the brackets and dashes be a frontend format only?

**Comment by ghost** [comment]
Currently it's set to be completely permissive, so any text string with a minimum of 10 digits will pass validation.

If we want to be  more strict about it, then I think we should use an external service to do the full validation.  Like this one from Twilio: https://www.twilio.com/lookup  

Using that service, we would store the  `"phone_number": "+14157012311"` value they return.
