### ISSUE TITLE
Retrieve Specialists (GPS based) returns all PBs on file regardless of coordinates?

### ISSUE THREAD

**Issue by iggbodiam** [workpathco/support#8]
{{base_url}}/specialists?page=1&limit=5&lat=36.691379&lon-85.134308&radius=1

currently the above link will return all PBs,  I tried several different locations and still go 7 specialists returned anywhere in the US.

Do we have no drive time distance limitation?
Are Specialists have no GPS coordinates set?
Do we have GPS diffrentiation of GPS based vs Home based depending on Today/Tomorrow(future) appointment date/time placement ?

**Comment by ghost** [comment]
> Do we have no drive time distance limitation?

Nope, only straight line distances.  The drive time calculations will happen on the phones in the context of specific appointments, if at all.

> Are Specialists have no GPS coordinates set?

No.  lat/lon are attributes on User

> Do we have GPS diffrentiation of GPS based vs Home based depending on Today/Tomorrow(future) appointment date/time placement ?

No.  The app is designed to use current location when appointment is same day, home location otherwise.
