### ISSUE TITLE
API: Populate specialist/practitioner in person responses

### ISSUE THREAD

**Issue by ghost** [workpathco/support#9]
We should eager load the practitioner/specialist/[any personable] association attribute when sending back a Person response.  Attributes need documented on Apiary

**Comment by amayers** [comment]
I've been thinking about this. Shouldn't it be `User.Specialist.Person` instead of `User.Person.Specialist`? Since all users are specialists and all specialists are people, but not all people are specialists?

**Comment by ghost** [comment]
Yeah this one is problematic, but Users can be Specialists or Practitioners or Patients.  So all Users are People, and People are optionally one of the other types.  

In any case, now we are populating `specialist`, `practitioner` or `patient` in the responses to `GET /people` and `GET /people/:id`

...aaand as I write that I realize I forgot about `GET /user/:id`.  :-1: Back in a second.

**Comment by ghost** [comment]
The person in the `GET /users/:id` now includes the specialist data.
